### ISSUE TITLE
Suggest using lager as your logging tool

### ISSUE THREAD

**Issue by jadeallenx** [gyanaggarwal/erlang_craq#1]
I'd like to suggest you use [lager](https://github.com/basho/lager) as your logging tool, or if you prefer something less coupled, consider using the [hut](https://github.com/tolbrino/hut) logging abstraction library.

**Comment by gyanaggarwal** [comment]
Thanks Mark.  I will look into both the options suggested by you.

**Comment by gyanaggarwal** [comment]
Lager logging framework has been added.

**Comment by gyanaggarwal** [comment]
Mark,

I have added lager logging framework. This has been added through a
sys.config parameter event_logger. This allows user to switch between lager
and gen_event logging.

All code changes (along with rebar, rebar.config, Makefile etc.) have been
pushed to Github.

Gyan

**Comment by jadeallenx** [comment]
:+1: Nice! Thanks.
